name: CI on Pull Request

on:
  pull_request:
    branches: [development]  
  push:
    branches: [main]          

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure push comes from development branch
        if: github.event_name == 'push'
        run: |
          # Verifica branch de origem do merge
          if [ "${{ github.event.head_commit.message }}" != *"Merge branch 'development'"* ]; then
            echo "Push para main só permitido a partir da branch development."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test -- --coverage
